### ISSUE TITLE
Untranslatable strings in the file browser

### ISSUE THREAD

**Issue by dikonov** [a-dekker/mediainfo-gui#7]
The file browser contains untranslatable menu entries (e.g. Scroll to top, Show Home, etc...). 
The root of the problem is that llc video player has no i18n suport. Fixing it here might be useful for the mother app as well.

**Comment by a-dekker** [comment]
llelectronics has abandoned this filemanager in favor of a more fancy one.
That leaves me to the choice of also replacing this part, or leave it as is. It will require some adaption to make it work for me. For now I decided to stay with this filemanager.

And I will consider looking at making it translatable if I do not switch to the new filemanager.

**Comment by a-dekker** [comment]
Strings made translatable: https://github.com/a-dekker/mediainfo-gui/commit/76288dcbe33a829e56e321ce1423d077abb62c5e
